services:
  db:
    image: postgres:15
    container_name: lefke_db
    env_file: .env  # Брать все из .env
    volumes:
      - postgres_data:/var/lib/postgresql/data # Данные БД не пропадут
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: lefke_redis
    ports:
      - "6379:6379"

  backend:
    build: .
    container_name: lefke_backend
    depends_on:
      - db
      - redis
    env_file: .env
    volumes:
      - .:/app              
      - ./uploads:/app/uploads # Папка для изображений
    ports:
      - "8000:8000"

volumes:
  postgres_data: