version: '3.8'

services:
  db:
    container_name: lefke-db
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: lefke-redis
    image: redis:7-alpine
    restart: always

  backend:
    container_name: lefke-backend
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - db
      - redis

  frontend:
    container_name: lefke-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Это связывает переменную из главного .env с процессом сборки
        - VITE_API_URL=${VITE_API_URL}
    restart: always
    # Весь твой сайт будет висеть на стандартном 80-м порту (HTTP)
    ports:
      - "8080:80"
    depends_on:
      - backend

  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./npm_data:/data
      - ./npm_letsencrypt:/etc/letsencrypt


volumes:
  postgres_data: