"""add_pgvector_and_embedding_column

Revision ID: 321f3841b33f
Revises: 7f1039837ee0
Create Date: 2026-04-29 14:03:24.728110

"""
import pgvector.sqlalchemy

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '321f3841b33f'
down_revision: Union[str, Sequence[str], None] = '7f1039837ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ads', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.alter_column('ads', 'price',
               existing_type=sa.NUMERIC(precision=7, scale=2),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ads', 'price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.NUMERIC(precision=7, scale=2),
               existing_nullable=False)
    op.drop_column('ads', 'embedding')
    # ### end Alembic commands ###
