"""add main_image and order

Revision ID: cd7d1c79e64d
Revises: 510951e5caa8
Create Date: 2026-03-17 23:18:05.352270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd7d1c79e64d'
down_revision: Union[str, Sequence[str], None] = '510951e5caa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad_images', sa.Column('order', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_ad_images_order'), 'ad_images', ['order'], unique=False)
    op.add_column('ads', sa.Column('main_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ads', 'main_image')
    op.drop_index(op.f('ix_ad_images_order'), table_name='ad_images')
    op.drop_column('ad_images', 'order')
    # ### end Alembic commands ###
